### PR TITLE
feat(helper): add unmanifested pack tag helpers

### LINKED ISSUE #21: Unmanifested Asset Helper
When using something like the DLL plugin, we are using a completely separate config to do that. Therefore, this file is not in the manifest, since we cannot share manifests between multiple webpack configs. 

That's okay for the moment because my team only uses the DLL plugin in development, so we can make sure to not hash the DLL plugin, and then we don't require reading from the manifest. However, we still need to properly grab the files from the correct webpack directory.

I am going to add two more methods to the API:

- `unmanifested_stylesheet_pack_tag`
- `unmanifested_javascript_pack_tag`

### PR DESCRIPTION
**Pull request by robwise**
Resolves #21

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/webpacker_lite/22)

### CODE REVIEW

**Comment by justin808** [comment]
I'm not clear on this one. A small example would be very helpful.

This sounds a bit like hot reloading in that there's no hash and special handling.

Could we do this with more options to the javascript_pack_tag rather than new helpers?

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/webpacker_lite/helper.rb, line 46 at r1](https://reviewable.io:443/reviews/shakacode/webpacker_lite/22#-KnUopwxbycpCmuKpu_A:-KnUopwxbycpCmuKpu_B:b-kwc44p) ([raw file](https://github.com/shakacode/webpacker_lite/blob/38775e12bd893974f5c88cf84b61f4b100a2fcb7/lib/webpacker_lite/helper.rb#L46)):*
> ```Ruby
>   #   # In production mode:
>   #   <%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %> # =>
>   #   <script src="/public/webpack/production/calendar.js" data-turbolinks-track="reload"></script>
> ```

I don't get how you output a non-hashed file in production mode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/webpacker_lite/22#-:-KnUp1qn5c7EQQ9PKB2b:b4775e6)*

**Comment by robwise** [comment]
> I'm not clear on this one. A small example would be very helpful.

I wrote a detailed explanation in the issue (#21). Did you read that?

> Could we do this with more options to the javascript_pack_tag rather than new helpers?

Yes, this is a style thing. We could either have a new method or keep the same method with a boolean flag. Usually, I get yelled at by the guys for doing boolean flags as that's considered a bit of a code smell, but I suppose we could do `manifested: false` or some such and default it to true? But then we'd have to pick it out of the rested named params which would be annoying.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[lib/webpacker_lite/helper.rb, line 46 at r1](https://reviewable.io:443/reviews/shakacode/webpacker_lite/22#-KnUopwxbycpCmuKpu_A:-KnXDZzZNfNKKoumYKT1:bxi53u7) ([raw file](https://github.com/shakacode/webpacker_lite/blob/38775e12bd893974f5c88cf84b61f4b100a2fcb7/lib/webpacker_lite/helper.rb#L46)):*
<details><summary><i>Previously, justin808 (Justin Gordon) wrote…</i></summary><blockquote>

I don't get how you output a non-hashed file in production mode.
</blockquote></details>

Well, that's easy, just don't tell webpack to do it. I think you mean why _would_  you? You probably wouldn't since you would have major caching problems. I can remove that part of the documentation, but technically, it _is_ possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/webpacker_lite/22#-:-KnXDt5h8MV-u61gOOcS:bh2bqwc)*

**Comment by justin808** [comment]
@robwise any comments on #20?

**Comment by robwise** [comment]
@justin808 What do I need to do to get this merged? Switch to a flag?

**Comment by robwise** [comment]
Closing because you can use the `cache` option for the manifest plugin to share a manifest between configs. See https://github.com/rails/webpacker/issues/464#issuecomment-313024512

**Pull request closed without merging**
